### ISSUE TITLE
Undefined names: 'conv' and 'Variable()'

### ISSUE THREAD

**Issue by cclauss** [google/sg2im#1]
Undefined names have the potential to raise NameError at runtime...

flake8 testing of https://github.com/google/sg2im on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./sg2im/layers.py:57:28: F821 undefined name 'conv'
    nn.init.kaiming_normal(conv.weight)
                           ^
./sg2im/layers.py:59:29: F821 undefined name 'conv'
    nn.init.kaiming_uniform(conv.weight)
                            ^
./sg2im/losses.py:152:11: F821 undefined name 'Variable'
  x_hat = Variable(x_hat, requires_grad=True)
          ^
3     F821 undefined name 'conv'
3
```

**Comment by jcjohnson** [comment]
Fixed in https://github.com/google/sg2im/commit/2a4126b6bf53e328c88065cc3c57bce9e58b08aa
